language: generic
sudo: required

services:
  - docker

before_install:
  - cd frontend
  - docker build -t mhtrimech/react-test -f Dockerfile.dev .

script:
  - docker run -e CI=true mhtrimech/react-test npm run test -- --coverage